# Generated by Django 2.2 on 2021-07-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='slug',
            field=models.SlugField(default='btc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='article_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='edited',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
