# Generated by Django 2.2 on 2022-01-14 12:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweden', '0002_auto_20210702_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='article')),
                ('meta_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('publish_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('B', 'blockchain'), ('G', 'guest_post'), ('CEX', 'centralized_crypto_exchange')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
