# Generated by Django 2.2 on 2022-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweden', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('B', 'blockchain'), ('news', 'nyheter'), ('G', 'guest_post'), ('wallet', 'crypto-wallet'), ('CEX', 'centralized-crypto-exchange')], max_length=50),
        ),
    ]
